### ISSUE TITLE
Implement Alignment UI as split button

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-alignment#4]
From @oleq's input from #2 about UI:

1. Each alignment style will have own UI toolbar button.
2. By default, the buttons will be aggregated in the group. 
    ![image](https://user-images.githubusercontent.com/1099479/32177260-206dfe88-bd8a-11e7-9f04-a98dfb88942f.png)
    It's a TODO because ATM there's no such possibility. Things to consider:
   0. A new UI component (dropdown) that groups other components is needed.
   1. How would toolbar config look like?
   2. Should it be configurable at all? Or maybe the `AlignmentUI` will provide the grouped buttons as w whole and to use them separately (4 buttons in the toolbar, next to each other) another UI will be required? This is a very generic problem for all our features.

**Comment by oleq** [comment]
@jodator There's already an [issue](https://github.com/ckeditor/ckeditor5-ui/issues/333) for the UI component. It should be developed there and used in alignment.

**Comment by dkonopka** [comment]
Regarding the issue [Shared UI and UX between CKEditor 5 and Letters](https://github.com/ckeditor/ckeditor5/issues/645) you can find here proposed design for dropdowns.

* dropdown arrow is separated element (`:after` pseudoelement or additional `<span>`)
* button with dropdown should be a little bit wider (in this design is +5px difference)

<img width="1506" alt="screen shot 2017-11-08 at 09 18 37" src="https://user-images.githubusercontent.com/10219857/32538307-d81c8cc0-c465-11e7-87e7-ec7fc7ba3f7e.png">

**Comment by fredck** [comment]
@dkonopka, your proposal is very good.

I would just include the default option (left align) in the list as well. Got confused by not seeing it in your images.

**Comment by dkonopka** [comment]
@fredck Currently design is showing an active state of `text-align: left` property, that's why it is not doubled in a dropdown. If user click right align icon it will change the place with active.

That's was just my idea to save some space, but it's only proposal, we can stay with KISS and do not complicate things.

<img width="943" alt="screen shot 2017-11-08 at 10 04 48" src="https://user-images.githubusercontent.com/10219857/32540229-54eb32dc-c46c-11e7-8e2b-36240fed332d.png">

**Comment by pjasiun** [comment]
I think that icon aggregation should be an until on top of having separate icons. I should be able to have these icons separated or group them in the drop-down. We could start from having icon aggregator designed for this feature and then make it more generic as a UI utlil.

**Comment by jodator** [comment]
@pjasiun: you mean this comment: https://github.com/ckeditor/ckeditor5-heading/issues/74#issuecomment-305224952 (own issue in: https://github.com/ckeditor/ckeditor5-ui/issues/322)

**Comment by Reinmar** [comment]
I think that we shouldn't release this feature without the dropdown, so I'm not going to include this in the upcoming alpha.2.

BTW, I'm not sure if this was discussed in some place, but I see this as two plugins – one proposing separate buttons and one proposing a dropdown. The same concept is planned for the heading feature (e.g. `HeadingButtons` and `HeadingDropdown`). Aggregation, while cool and needed at some point, is a separate feature and I'd propose to not spend time on it just yet. It can be added later. Having more editing features first should be, IMO, our priority.

**Comment by oleq** [comment]
@jodator Can you create a PR out of https://github.com/ckeditor/ckeditor5-alignment/blob/t/4 so we can comment?

----

For now, I'll leave my quick comments here:

* The editing view must be [focused](https://github.com/ckeditor/ckeditor5-heading/blob/33122932b72e6919377254d719b6db7a87813ca2/src/heading.js#L109-L112) upon execution of the button: https://github.com/ckeditor/ckeditor5-alignment/blob/378ddf13e07dbf1d40fdfa6c92fde2426a32220d/src/alignmentui.js#L127 Otherwise, when navigating using the keyboard, if pressed <kbd>Enter</kbd>, the selection is lost in the editor.
* Just like other buttons in the toolbar, when under `.ck-editor-toolbar`, the drop-down should have [no background/border](https://github.com/ckeditor/ckeditor5-theme-lark/blob/master/theme/components/editor.scss#L23-L34). It's a button with some extra features rather than just a regular drop-down.
* A focused button in the drop-down should have higher z-index to avoid focus outlines overlapping. 
![image](https://user-images.githubusercontent.com/1099479/32718363-37d659b6-c85d-11e7-820f-67657499bc15.png)
* Any button in the drop-down should have no border-radius (image above).

I didn't have much time to read all the code, especially in ckeditor5-ui, but it looks and works great 🎉 Waiting for PRs in both repos so we can get into details ;-)
